### ISSUE TITLE
等更新Waiting for update

### ISSUE THREAD

**Issue by Maybe0019** [bin456789/Unblock163MusicClient-Xposed#163]
云村5.6的音量.27不够大了

**Comment by Maybe0019** [comment]
at bin.xposed.Unblock163MusicClient.a$c.a(Unknown Source:151)
10-31 00:43:47.130 E/Xposed  (26204): 	at bin.xposed.Unblock163MusicClient.a.a(Unknown Source:21)
10-31 00:43:47.130 E/Xposed  (26204): 	at bin.xposed.Unblock163MusicClient.Main$1.afterHookedMethod(Unknown Source:21)
10-31 00:43:47.130 E/Xposed  (26204): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:375)
10-31 00:43:47.130 E/Xposed  (26204): 	at android.app.Application.attach(<Xposed>)
10-31 00:43:47.130 E/Xposed  (26204): 	at android.app.Instrumentation.newApplication(Instrumentation.java:1103)
10-31 00:43:47.130 E/Xposed  (26204): 	at android.app.Instrumentation.newApplication(Instrumentation.java:1087)
10-31 00:43:47.130 E/Xposed  (26204): 	at android.app.LoadedApk.makeApplication(LoadedApk.java:972)
10-31 00:43:47.130 E/Xposed  (26204): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5851)
10-31 00:43:47.130 E/Xposed  (26204): 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
10-31 00:43:47.130 E/Xposed  (26204): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:361)
10-31 00:43:47.130 E/Xposed  (26204): 	at android.app.ActivityThread.handleBindApplication(<Xposed>)
10-31 00:43:47.130 E/Xposed  (26204): 	at android.app.ActivityThread.-wrap1(Unknown Source:0)
10-31 00:43:47.130 E/Xposed  (26204): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1690)
10-31 00:43:47.130 E/Xposed  (26204): 	at android.os.Handler.dispatchMessage(Handler.java:105)
10-31 00:43:47.130 E/Xposed  (26204): 	at android.os.Looper.loop(Looper.java:173)
10-31 00:43:47.130 E/Xposed  (26204): 	at android.app.ActivityThread.main(ActivityThread.java:6698)
10-31 00:43:47.130 E/Xposed  (26204): 	at java.lang.reflect.Method.invoke(Native Method)
10-31 00:43:47.130 E/Xposed  (26204): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
10-31 00:43:47.130 E/Xposed  (26204): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782)
10-31 00:43:47.130 E/Xposed  (26204): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:108)
10-31 00:43:49.857 E/Xposed  (26274): java.util.NoSuchElementException: No value present
10-31 00:43:49.857 E/Xposed  (26274): 	at a.a.a.e.b(Unknown Source:8)
10-31 00:43:49.857 E/Xposed  (26274): 	at bin.xposed.Unblock163MusicClient.a$c.a(Unknown Source:151)
10-31 00:43:49.857 E/Xposed  (26274): 	at bin.xposed.Unblock163MusicClient.a.a(Unknown Source:21)
10-31 00:43:49.857 E/Xposed  (26274): 	at bin.xposed.Unblock163MusicClient.Main$1.afterHookedMethod(Unknown Source:21)
10-31 00:43:49.857 E/Xposed  (26274): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:375)
10-31 00:43:49.857 E/Xposed  (26274): 	at android.app.Application.attach(<Xposed>)
部分log（不怎么会抓），应该就是没更新，不支持新版本～作者可能比较忙吧

**Comment by herexf** [comment]
没办法，网易也知道这个的存在，新版代码做了些调整，因为一帮人不停的在各平台的网易云音乐下晒着他们的音量…

甚至以后会检测安装app清单了，如果有这个包名，就不让启动，按照国内app的尿性，不是没可能

**Comment by whc2001** [comment]
建议用回老版本, 这边测试4.0.1仍可以正常使用. 检测Xposed好像早就有在做了, 之前更新到某个新版本的时候一直闪退, 卸载插件也无效, 卸载Xposed才正常, XposedHider无效, 退回老版本才可正常使用.
