### ISSUE TITLE
新版空指针

### ISSUE THREAD

**Issue by aviraxp** [bin456789/Unblock163MusicClient-Xposed#29]
能使用，但是歌名是灰的。网易云是http://soft.shouji.com.cn/down/25231.html

```
11-06 22:34:17.925 E/Xposed  ( 8034): java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.startsWith(java.lang.String)' on a null object reference
11-06 22:34:17.925 E/Xposed  ( 8034):      at bin.xposed.Unblock163MusicClient.a$e.a(Unknown Source)
11-06 22:34:17.925 E/Xposed  ( 8034):      at bin.xposed.Unblock163MusicClient.Main$1$7.beforeHookedMethod(Unknown Source)
11-06 22:34:17.925 E/Xposed  ( 8034):      at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:314)
11-06 22:34:17.925 E/Xposed  ( 8034):      at com.netease.cloudmusic.meta.MusicInfo.getAppendCopyRight(<Xposed>)
11-06 22:34:17.925 E/Xposed  ( 8034):      at com.netease.cloudmusic.activity.i.am(ProGuard:693)
11-06 22:34:17.925 E/Xposed  ( 8034):      at com.netease.cloudmusic.ui.LyricView.a(ProGuard:1106)
11-06 22:34:17.925 E/Xposed  ( 8034):      at com.netease.cloudmusic.ui.LyricView.setMsg(ProGuard:1101)
11-06 22:34:17.925 E/Xposed  ( 8034):      at com.netease.cloudmusic.ui.LyricView.a(ProGuard:275)
11-06 22:34:17.925 E/Xposed  ( 8034):      at com.netease.cloudmusic.ui.LyricView.a(ProGuard:152)
11-06 22:34:17.925 E/Xposed  ( 8034):      at com.netease.cloudmusic.activity.PlayerActivity.M(ProGuard:242)
11-06 22:34:17.925 E/Xposed  ( 8034):      at com.netease.cloudmusic.activity.h$13.onClick(ProGuard:924)
11-06 22:34:17.925 E/Xposed  ( 8034):      at android.view.View.performClick(View.java:5205)
11-06 22:34:17.925 E/Xposed  ( 8034):      at android.view.View$PerformClick.run(View.java:21166)
11-06 22:34:17.925 E/Xposed  ( 8034):      at android.os.Handler.handleCallback(Handler.java:739)
11-06 22:34:17.925 E/Xposed  ( 8034):      at android.os.Handler.dispatchMessage(Handler.java:95)
11-06 22:34:17.925 E/Xposed  ( 8034):      at android.os.Looper.loop(Looper.java:148)
11-06 22:34:17.925 E/Xposed  ( 8034):      at android.app.ActivityThread.main(ActivityThread.java:5481)
11-06 22:34:17.925 E/Xposed  ( 8034):      at java.lang.reflect.Method.invoke(Native Method)
11-06 22:34:17.925 E/Xposed  ( 8034):      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
11-06 22:34:17.925 E/Xposed  ( 8034):      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
11-06 22:34:17.925 E/Xposed  ( 8034):      at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
```

**Comment by aviraxp** [comment]
还是灰的，虽然不扔空指针了
